POST http://localhost:1897/hook
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/95a0199
X-GitHub-Delivery: 7b0a9784-bbf0-11e7-9464-85227e78a371
X-GitHub-Event: push

{"ref":"refs/heads/1.10"}